/* This file is autogenerated. Look at src/tools/code-gen */

import { DeviceRequestType } from '../model/device-request-type';
import {
  CompoteDaily,
  Dose,
  Mixer,
  Program,
  Pump,
  Schedule,
  Timer,
} from './struct';
export interface DeviceRequestFertigate {
  type: DeviceRequestType.fertigate;
  payload: {
    programId: number;
  };
}
export interface DeviceRequestIrrigate {
  type: DeviceRequestType.irrigate;
  payload: {
    programId: number;
  };
}
export interface DeviceRequestWash {
  type: DeviceRequestType.wash;
  payload: {
    programId: number;
  };
}
export interface DeviceRequestPumpIn {
  type: DeviceRequestType.pumpIn;
  payload: {
    programId: number;
  };
}
export interface DeviceRequestCompote {
  type: DeviceRequestType.compote;
  payload: {
    programId: number;
  };
}
export interface DeviceRequestWashCompote {
  type: DeviceRequestType.washCompote;
  payload: {
    programId: number;
  };
}
export interface DeviceRequestMix {
  type: DeviceRequestType.mix;
  payload: {
    mixerId: number;
  };
}
export interface DeviceRequestMixDose {
  type: DeviceRequestType.mixDose;
  payload: {
    mixerId: number;
  };
}
export interface DeviceRequestDose {
  type: DeviceRequestType.dose;
  payload: {
    programId: number;
    doseId: number;
  };
}
export interface DeviceRequestGetProgram {
  type: DeviceRequestType.getProgram;
  payload: {
    index: number;
  };
}
export interface DeviceRequestSetProgram {
  type: DeviceRequestType.setProgram;
  payload: {
    index: number;
    value: Program;
  };
}
export interface DeviceRequestGetCompoteDaily {
  type: DeviceRequestType.getCompoteDaily;
  payload: {
    index: number;
    dailyIndex: number;
  };
}
export interface DeviceRequestSetCompoteDaily {
  type: DeviceRequestType.setCompoteDaily;
  payload: {
    index: number;
    dailyIndex: number;
    value: CompoteDaily;
  };
}
export interface DeviceRequestGetSchedule {
  type: DeviceRequestType.getSchedule;
  payload: {
    index: number;
  };
}
export interface DeviceRequestSetSchedule {
  type: DeviceRequestType.setSchedule;
  payload: {
    index: number;
    value: Schedule;
  };
}
export interface DeviceRequestGetTimer {
  type: DeviceRequestType.getTimer;
  payload: {
    index: number;
  };
}
export interface DeviceRequestSetTimer {
  type: DeviceRequestType.setTimer;
  payload: {
    index: number;
    value: Timer;
  };
}
export interface DeviceRequestGetPump {
  type: DeviceRequestType.getPump;
  payload: {
    index: number;
  };
}
export interface DeviceRequestSetPump {
  type: DeviceRequestType.setPump;
  payload: {
    index: number;
    value: Pump;
  };
}
export interface DeviceRequestGetMixer {
  type: DeviceRequestType.getMixer;
  payload: {
    index: number;
  };
}
export interface DeviceRequestSetMixer {
  type: DeviceRequestType.setMixer;
  payload: {
    index: number;
    value: Mixer;
  };
}
export interface DeviceRequestGetDose {
  type: DeviceRequestType.getDose;
  payload: {
    index: number;
  };
}
export interface DeviceRequestSetDose {
  type: DeviceRequestType.setDose;
  payload: {
    index: number;
    value: Dose;
  };
}
export interface DeviceRequestGetPinPump {
  type: DeviceRequestType.getPinPump;
  payload: {
    index: number;
  };
}
export interface DeviceRequestSetPinPump {
  type: DeviceRequestType.setPinPump;
  payload: {
    index: number;
    value: number;
  };
}
export interface DeviceRequestGetPinFlowSensor {
  type: DeviceRequestType.getPinFlowSensor;
  payload: {
    index: number;
  };
}
export interface DeviceRequestSetPinFlowSensor {
  type: DeviceRequestType.setPinFlowSensor;
  payload: {
    index: number;
    value: number;
  };
}
export interface DeviceRequestGetPinLevelSensor {
  type: DeviceRequestType.getPinLevelSensor;
  payload: {
    index: number;
  };
}
export interface DeviceRequestSetPinLevelSensor {
  type: DeviceRequestType.setPinLevelSensor;
  payload: {
    index: number;
    value: number;
  };
}
export interface DeviceRequestGetPinMixer {
  type: DeviceRequestType.getPinMixer;
  payload: {
    index: number;
  };
}
export interface DeviceRequestSetPinMixer {
  type: DeviceRequestType.setPinMixer;
  payload: {
    index: number;
    value: number;
  };
}
export interface DeviceRequestGetPinDose {
  type: DeviceRequestType.getPinDose;
  payload: {
    index: number;
  };
}
export interface DeviceRequestSetPinDose {
  type: DeviceRequestType.setPinDose;
  payload: {
    index: number;
    value: number;
  };
}
export interface DeviceRequestGetPinDoseMixer {
  type: DeviceRequestType.getPinDoseMixer;
  payload: {
    index: number;
  };
}
export interface DeviceRequestSetPinDoseMixer {
  type: DeviceRequestType.setPinDoseMixer;
  payload: {
    index: number;
    value: number;
  };
}
export interface DeviceRequestGetPinValve {
  type: DeviceRequestType.getPinValve;
  payload: {
    index: number;
  };
}
export interface DeviceRequestSetPinValve {
  type: DeviceRequestType.setPinValve;
  payload: {
    index: number;
    value: number;
  };
}
export interface DeviceRequestGetTime {
  type: DeviceRequestType.getTime;
  payload: {
    fake: number;
  };
}
export interface DeviceRequestSetTime {
  type: DeviceRequestType.setTime;
  payload: {
    second: number;
    minute: number;
    hour: number;
    wday: number;
    day: number;
    month: number;
    year: number;
  };
}
export interface DeviceRequestGetTemp {
  type: DeviceRequestType.getTemp;
  payload: {
    fake: number;
  };
}
export interface DeviceRequestGetStatus {
  type: DeviceRequestType.getStatus;
  payload: {
    fake: number;
  };
}
export interface DeviceRequestGetStatePump {
  type: DeviceRequestType.getStatePump;
  payload: {
    index: number;
  };
}
export interface DeviceRequestSetStatePump {
  type: DeviceRequestType.setStatePump;
  payload: {
    index: number;
    value: number;
  };
}
export interface DeviceRequestGetStateValve {
  type: DeviceRequestType.getStateValve;
  payload: {
    index: number;
  };
}
export interface DeviceRequestSetStateValve {
  type: DeviceRequestType.setStateValve;
  payload: {
    index: number;
    value: number;
  };
}
export interface DeviceRequestGetStateMixer {
  type: DeviceRequestType.getStateMixer;
  payload: {
    index: number;
  };
}
export interface DeviceRequestSetStateMixer {
  type: DeviceRequestType.setStateMixer;
  payload: {
    index: number;
    value: number;
  };
}
export interface DeviceRequestGetStateDose {
  type: DeviceRequestType.getStateDose;
  payload: {
    index: number;
  };
}
export interface DeviceRequestSetStateDose {
  type: DeviceRequestType.setStateDose;
  payload: {
    index: number;
    value: number;
  };
}
export interface DeviceRequestGetStateDoseMixer {
  type: DeviceRequestType.getStateDoseMixer;
  payload: {
    index: number;
  };
}
export interface DeviceRequestSetStateDoseMixer {
  type: DeviceRequestType.setStateDoseMixer;
  payload: {
    index: number;
    value: number;
  };
}
export interface DeviceRequestResetError {
  type: DeviceRequestType.resetError;
  payload: {
    fake: number;
  };
}
export type DeviceRequest =
  | DeviceRequestFertigate
  | DeviceRequestIrrigate
  | DeviceRequestWash
  | DeviceRequestPumpIn
  | DeviceRequestCompote
  | DeviceRequestWashCompote
  | DeviceRequestMix
  | DeviceRequestMixDose
  | DeviceRequestDose
  | DeviceRequestGetProgram
  | DeviceRequestSetProgram
  | DeviceRequestGetCompoteDaily
  | DeviceRequestSetCompoteDaily
  | DeviceRequestGetSchedule
  | DeviceRequestSetSchedule
  | DeviceRequestGetTimer
  | DeviceRequestSetTimer
  | DeviceRequestGetPump
  | DeviceRequestSetPump
  | DeviceRequestGetMixer
  | DeviceRequestSetMixer
  | DeviceRequestGetDose
  | DeviceRequestSetDose
  | DeviceRequestGetPinPump
  | DeviceRequestSetPinPump
  | DeviceRequestGetPinFlowSensor
  | DeviceRequestSetPinFlowSensor
  | DeviceRequestGetPinLevelSensor
  | DeviceRequestSetPinLevelSensor
  | DeviceRequestGetPinMixer
  | DeviceRequestSetPinMixer
  | DeviceRequestGetPinDose
  | DeviceRequestSetPinDose
  | DeviceRequestGetPinDoseMixer
  | DeviceRequestSetPinDoseMixer
  | DeviceRequestGetPinValve
  | DeviceRequestSetPinValve
  | DeviceRequestGetTime
  | DeviceRequestSetTime
  | DeviceRequestGetTemp
  | DeviceRequestGetStatus
  | DeviceRequestGetStatePump
  | DeviceRequestSetStatePump
  | DeviceRequestGetStateValve
  | DeviceRequestSetStateValve
  | DeviceRequestGetStateMixer
  | DeviceRequestSetStateMixer
  | DeviceRequestGetStateDose
  | DeviceRequestSetStateDose
  | DeviceRequestGetStateDoseMixer
  | DeviceRequestSetStateDoseMixer
  | DeviceRequestResetError;
